module.exports = [
  {
    id: 1,
    name: "Peri Peri Chicken Burger",
    cost: 99,
    veg_status: 0,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/kfg7lrzaewsfji6aonik",
    bestseller_status: 1,
    category_id: 1,
    description: "",
    category: "Recommended",
  },
  {
    id: 2,
    name: "Paneer Burger",
    cost: 120,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/kfg7lrzaewsfji6aonik",
    bestseller_status: 1,
    category_id: 1,
    description: "",
    category: "Recommended",
  },
  {
    id: 3,
    name: "Super Veggie Burger",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 1,
    description: "",
    category: "Recommended",
  },
  {
    id: 4,
    name: "Mini Veg Burger",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 2,
    description: "",
    category: "Burgers",
  },
  {
    id: 5,
    name: "Mini Veg Burger (Meal)",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 2,
    description: "",
    category: "Burgers",
  },
  {
    id: 6,
    name: "Mini Veg Burger (Meal)",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 2,
    description: "",
    category: "Burgers",
  },
  {
    id: 7,
    name: "Mini Snacker Burger",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 6,
    description: "",
    category: "Desert",
  },
  {
    id: 8,
    name: "Mini Snacker Meal",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 3,
    description: "",
    category: "Kids Meal",
  },
  {
    id: 9,
    name: "Nuggets Meal",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 3,
    description: "",
    category: "Kids Meal",
  },
  {
    id: 10,
    name: "Mini Snacker Burger",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 3,
    description: "",
    category: "Kids Meal",
  },
  {
    id: 11,
    name: "Zinger Chicken Meal",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 6,
    description: "",
    category: "Desert",
  },
  {
    id: 12,
    name: "Grilled Chicken Meal",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 4,
    description: "",
    category: "Value Meal",
  },
  {
    id: 13,
    name: "Fried Chicken Meal",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 4,
    description: "",
    category: "Value Meal",
  },
  {
    id: 14,
    name: "Fried Chicken (8 Pcs)",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 5,
    description: "",
    category: "Family Meals",
  },
  {
    id: 15,
    name: "Fried Chicken (16 Pcs)",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 5,
    description: "",
    category: "Family Meals",
  },
  {
    id: 16,
    name: "Grilled Chicken (8 Pcs)",
    cost: 85,
    veg_status: 1,
    img_src: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/i1ym6cko9bzjjdsx9npm",
    bestseller_status: 1,
    category_id: 5,
    description: "",
    category: "Family Meals",
  },
];
