module.exports = [
  {
    id: 1,
    imgsrc: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/gzpbhaspfffv0z2owguf",
    name: "Fried Chicken Cuisine-FCC",
    description: "American, Fast Food",
    rating: 4.3,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 2,
    imgsrc: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/yq6bc70klxog72q6fcy6",
    name: "Fast Food, Pastas, Pizzas",
    description: "North Indian, Home Food, Combo, Desserts, Beverages, Snacks",
    rating: 4.2,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 3,
    imgsrc: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/dui3oalkmdve7dtwklad",
    name: "Medha Malvan",
    description: "Malwani, Seafood",
    rating: 4.4,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 4,
    imgsrc: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/pvzbvtqsuzh06pvrwrwl",
    name: "Yum Yum Chi",
    description: "Chinese, Continental, Pan-Asian",
    rating: 4.4,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 5,
    imgsrc: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/ipuppwyw0tjuap5wrwxu",
    name: "Chai Point",
    description: "Healthy Food, Bakery, Cafe, Combo, Beverages, Maharashtrian, Snacks,",
    rating: 3,
    rating_vote: 251,
    avg_cost: 150,
    location: "parel, Mumbai",
  },
  {
    id: 6,
    imgsrc: "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/fvtpvqzgjfrt8cyfef5p",
    name: "Birdy's Cake Shop",
    description: "Desserts, Fast Food, Bakery",
    rating: 5,
    rating_vote: 251,
    avg_cost: 1550,
    location: "parel, Mumbai",
  },
];
