module.exports = [
  {
    id: 1,
    imgsrc: "https://www.swiggy.com/restaurants/fried-chicken-cuisine-fcc-sv-road-byculla-mumbai-26838",
    name: "Fried Chicken Cuisine-FCC",
    description: "American, Fast Food",
    rating: 4.3,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 2,
    imgsrc: "https://www.swiggy.com/restaurants/cafe-2-0-lalbaug-parel-mumbai-60907",
    name: "Fast Food, Pastas, Pizzas",
    description: "North Indian, Home Food, Combo, Desserts, Beverages, Snacks",
    rating: 4.2,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 3,
    imgsrc: "https://www.swiggy.com/restaurants/medha-malvan-lower-parel-worli-mumbai-354577",
    name: "Medha Malvan",
    description: "Malwani, Seafood",
    rating: 4.4,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
  {
    id: 4,
    imgsrc: "https://www.swiggy.com/restaurants/yum-yum-chi-chowpatty-mumbai-295912",
    name: "Yum Yum Chi",
    description: "Chinese, Continental, Pan-Asian",
    rating: 4.4,
    rating_vote: 251,
    avg_cost: 350,
    location: "parel, Mumbai",
  },
];
